/* Generated By:JavaCC: Do not edit this line. XfuzzyConfigConstants.java */
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//   PARSER DE LA CONFIGURACION DE LAS DISTINTAS HERRAMIENTAS	//
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++//

package xfuzzy;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface XfuzzyConfigConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 3;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT2 = 4;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int XFSL_TRAININGFILE = 6;
  /** RegularExpression Id. */
  int XFSL_TESTFILE = 7;
  /** RegularExpression Id. */
  int XFSL_LOGFILE = 8;
  /** RegularExpression Id. */
  int XFSL_OUTPUTFILE = 9;
  /** RegularExpression Id. */
  int XFSL_ALGORITHM = 10;
  /** RegularExpression Id. */
  int XFSL_OPTION = 11;
  /** RegularExpression Id. */
  int XFSL_ERRORFUNCTION = 12;
  /** RegularExpression Id. */
  int XFSL_PREPROCESSING = 13;
  /** RegularExpression Id. */
  int XFSL_POSTPROCESSING = 14;
  /** RegularExpression Id. */
  int XFSL_ENDCONDITION = 15;
  /** RegularExpression Id. */
  int XFSL_ENABLE = 16;
  /** RegularExpression Id. */
  int XFSL_DISABLE = 17;
  /** RegularExpression Id. */
  int XFSIM_PLANT = 18;
  /** RegularExpression Id. */
  int XFSIM_INIT = 19;
  /** RegularExpression Id. */
  int XFSIM_LIMIT = 20;
  /** RegularExpression Id. */
  int XFSIM_LOG = 21;
  /** RegularExpression Id. */
  int XFSIM_PLOT = 22;
  /** RegularExpression Id. */
  int XFPLOT_GRAPH3D = 23;
  /** RegularExpression Id. */
  int XFPLOT_GRAPH2D = 24;
  /** RegularExpression Id. */
  int XFPLOT_VALUES = 25;
  /** RegularExpression Id. */
  int XFPLOT_PERSPECTIVE = 26;
  /** RegularExpression Id. */
  int XFPLOT_SAMPLES = 27;
  /** RegularExpression Id. */
  int XFPLOT_COLORMODE = 28;
  /** RegularExpression Id. */
  int XFDM_PATTERN = 29;
  /** RegularExpression Id. */
  int XFDM_INPUTS = 30;
  /** RegularExpression Id. */
  int XFDM_OUTPUTS = 31;
  /** RegularExpression Id. */
  int XFDM_INPUT = 32;
  /** RegularExpression Id. */
  int XFDM_SYSTEM = 33;
  /** RegularExpression Id. */
  int XFDM_ALGORITHM = 34;
  /** RegularExpression Id. */
  int EOL = 35;
  /** RegularExpression Id. */
  int OTHER = 36;
  /** RegularExpression Id. */
  int CEOL = 37;
  /** RegularExpression Id. */
  int ID = 38;
  /** RegularExpression Id. */
  int FILE = 39;
  /** RegularExpression Id. */
  int PARAM = 40;
  /** RegularExpression Id. */
  int NUMBER = 41;
  /** RegularExpression Id. */
  int INTEGER = 42;
  /** RegularExpression Id. */
  int FLOAT = 43;
  /** RegularExpression Id. */
  int ERROR = 44;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"//\"",
    "\"#\"",
    "<MULTI_LINE_COMMENT>",
    "\"xfsl_training\"",
    "\"xfsl_test\"",
    "\"xfsl_log\"",
    "\"xfsl_output\"",
    "\"xfsl_algorithm\"",
    "\"xfsl_option\"",
    "\"xfsl_errorfunction\"",
    "\"xfsl_preprocessing\"",
    "\"xfsl_postprocessing\"",
    "\"xfsl_endcondition\"",
    "\"xfsl_enable\"",
    "\"xfsl_disable\"",
    "\"xfsim_plant\"",
    "\"xfsim_init\"",
    "\"xfsim_limit\"",
    "\"xfsim_log\"",
    "\"xfsim_plot\"",
    "\"xfplot_graph3D\"",
    "\"xfplot_graph2D\"",
    "\"xfplot_values\"",
    "\"xfplot_perspective\"",
    "\"xfplot_samples\"",
    "\"xfplot_colormode\"",
    "\"xfdm_pattern\"",
    "\"xfdm_inputs\"",
    "\"xfdm_outputs\"",
    "\"xfdm_input\"",
    "\"xfdm_system\"",
    "\"xfdm_algorithm\"",
    "<EOL>",
    "<OTHER>",
    "<CEOL>",
    "<ID>",
    "<FILE>",
    "<PARAM>",
    "<NUMBER>",
    "<INTEGER>",
    "<FLOAT>",
    "<ERROR>",
    "\"(\"",
    "\")\"",
    "\"&\"",
    "\",\"",
    "\"<\"",
    "\">\"",
  };

}
