//+++++++++++++++++++++++++++++++++++++++++++++++++++++
// File automatically generated by Xfuzzy - DO NOT EDIT
//+++++++++++++++++++++++++++++++++++++++++++++++++++++

package pkg.xfl.binary;

import xfuzzy.lang.*;

public class bounded_prod extends Binary {
 public bounded_prod() {
   super("xfl","bounded_prod");
   Parameter single[] = new Parameter[0];
   setSingleParameters(single);
  }

 public double compute(double a, double b) {
 return (a+b-1>0? a+b-1: 0); 
  }

 public double[] derivative(double a, double b) {
   double[] deriv = new double[2];
  deriv[0] = (a+b-1>0? 1: (a+b==1? 0.5 : 0));
  deriv[1] = (a+b-1>0? 1: (a+b==1? 0.5 : 0));
   return deriv;
  }

 public boolean test () {
   return true;
  }

 public String getJavaCode() {
   String eol = System.getProperty("line.separator", "\n");
   String code = "";
   code += "    return (a+b-1>0? a+b-1: 0); "+eol;
   return code;
  }

 public String getCCode() {
   String eol = System.getProperty("line.separator", "\n");
   String code = "";
   code += "    return (a+b-1>0? a+b-1: 0); "+eol;
   return code;
  }

 public String getCppCode() {
   String eol = System.getProperty("line.separator", "\n");
   String code = "";
   code += "    return (a+b-1>0? a+b-1: 0); "+eol;
   return code;
  }
}
