/* Generated By:JavaCC: Do not edit this line. XftspConfigParserConstants.java */
/*
 * Parser for xftsp configuration files
 */

package xfuzzy.xftsp.cfgparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface XftspConfigParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 3;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT2 = 4;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int XFTSP_SERIES_NAME = 6;
  /** RegularExpression Id. */
  int XFTSP_TRAINING_FILE = 7;
  /** RegularExpression Id. */
  int XFTSP_TEST_FILE = 8;
  /** RegularExpression Id. */
  int XFTSP_OPTION = 9;
  /** RegularExpression Id. */
  int XFTSP_ID_ALGORITHM = 10;
  /** RegularExpression Id. */
  int XFTSP_OPT_ALGORITHM = 11;
  /** RegularExpression Id. */
  int XFTSP_SELECTION = 12;
  /** RegularExpression Id. */
  int XFTSP_NRVE = 13;
  /** RegularExpression Id. */
  int EOL = 14;
  /** RegularExpression Id. */
  int OTHER = 15;
  /** RegularExpression Id. */
  int CEOL = 16;
  /** RegularExpression Id. */
  int ID = 17;
  /** RegularExpression Id. */
  int FILE = 18;
  /** RegularExpression Id. */
  int PARAM = 19;
  /** RegularExpression Id. */
  int NUMBER = 20;
  /** RegularExpression Id. */
  int INTEGER = 21;
  /** RegularExpression Id. */
  int FLOAT = 22;
  /** RegularExpression Id. */
  int ERROR = 23;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"//\"",
    "\"#\"",
    "<MULTI_LINE_COMMENT>",
    "\"xftsp_series_name\"",
    "\"xftsp_training_file\"",
    "\"xftsp_test_file\"",
    "\"xftsp_option\"",
    "\"xftsp_id_algorithm\"",
    "\"xftsp_opt_algorithm\"",
    "\"xftsp_selection\"",
    "\"xftsp_nrve\"",
    "<EOL>",
    "<OTHER>",
    "<CEOL>",
    "<ID>",
    "<FILE>",
    "<PARAM>",
    "<NUMBER>",
    "<INTEGER>",
    "<FLOAT>",
    "<ERROR>",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
