//+++++++++++++++++++++++++++++++++++++++++++++++++++++
// File automatically generated by Xfuzzy - DO NOT EDIT
//+++++++++++++++++++++++++++++++++++++++++++++++++++++

package pkg.xfsg.crisp;

import xfuzzy.lang.*;

public class diffDeg extends CrispBlock {
 public diffDeg() {
   super("xfsg","diffDeg");
   Parameter single[] = new Parameter[0];
   setSingleParameters(single);
  }

 public double compute(double[] x) {
  double d = x[0] - x[1];
  if(d>180) d -= 360;
  if(d<-180) d += 360;
  return d;
  }

 public int inputs() {
 return 2; 
  }

 public boolean test () {
   return true;
  }

 public String getJavaCode() {
   String eol = System.getProperty("line.separator", "\n");
   String code = "";
   code += "     double d = x[0] - x[1];"+eol;
   code += "     if(d>180) d -= 360;"+eol;
   code += "     if(d<-180) d += 360;"+eol;
   code += "     return d;"+eol;
   return code;
  }

 public String getCCode() {
   String eol = System.getProperty("line.separator", "\n");
   String code = "";
   code += "     double d = x[0] - x[1];"+eol;
   code += "     if(d>180) d -= 360;"+eol;
   code += "     if(d<-180) d += 360;"+eol;
   code += "     return d;"+eol;
   return code;
  }

 public String getCppCode() {
   String eol = System.getProperty("line.separator", "\n");
   String code = "";
   code += "     double d = x[0] - x[1];"+eol;
   code += "     if(d>180) d -= 360;"+eol;
   code += "     if(d<-180) d += 360;"+eol;
   code += "     return d;"+eol;
   return code;
  }
}
