//+++++++++++++++++++++++++++++++++++++++++++++++++++++
// File automatically generated by Xfuzzy - DO NOT EDIT
//+++++++++++++++++++++++++++++++++++++++++++++++++++++

package pkg.xfl.unary;

import xfuzzy.lang.*;

public class edge extends Unary {
 public edge() {
   super("xfl","edge");
   Parameter single[] = new Parameter[0];
   setSingleParameters(single);
  }

 public double compute(double a) {
 return (a<=0.5? 2*a : 2*(1-a) ); 
  }

 public double derivative(double a) {
   double deriv;
 deriv = (a<0.5? 2 : (a>0.5? -2 : 0)); 
   return deriv;
  }

 public boolean test () {
   return true;
  }

 public String getJavaCode() {
   String eol = System.getProperty("line.separator", "\n");
   String code = "";
   code += "    return (a<=0.5? 2*a : 2*(1-a) ); "+eol;
   return code;
  }

 public String getCCode() {
   String eol = System.getProperty("line.separator", "\n");
   String code = "";
   code += "    return  (a<=0.5? 2*a : 2*(1-a) ); "+eol;
   return code;
  }

 public String getCppCode() {
   String eol = System.getProperty("line.separator", "\n");
   String code = "";
   code += "    return  (a<=0.5? 2*a : 2*(1-a) ); "+eol;
   return code;
  }
}
