//+++++++++++++++++++++++++++++++++++++++++++++++++++++
// File automatically generated by Xfuzzy - DO NOT EDIT
//+++++++++++++++++++++++++++++++++++++++++++++++++++++

package pkg.xfl.unary;

import xfuzzy.lang.*;

public class sqrt extends Unary {
 public sqrt() {
   super("xfl","sqrt");
   Parameter single[] = new Parameter[0];
   setSingleParameters(single);
  }

 public double compute(double a) {
 return Math.sqrt(a); 
  }

 public double derivative(double a) {
   double deriv;
 deriv = 1/(2*Math.sqrt(a)); 
   return deriv;
  }

 public boolean test () {
   return true;
  }

 public String getJavaCode() {
   String eol = System.getProperty("line.separator", "\n");
   String code = "";
   code += "    return Math.sqrt(a); "+eol;
   return code;
  }

 public String getCCode() {
   String eol = System.getProperty("line.separator", "\n");
   String code = "";
   code += "    return sqrt(a); "+eol;
   return code;
  }

 public String getCppCode() {
   String eol = System.getProperty("line.separator", "\n");
   String code = "";
   code += "    return sqrt(a); "+eol;
   return code;
  }
}
