//+++++++++++++++++++++++++++++++++++++++++++++++++++++
// File automatically generated by Xfuzzy - DO NOT EDIT
//+++++++++++++++++++++++++++++++++++++++++++++++++++++

package pkg.xfl.unary;

import xfuzzy.lang.*;

public class sugeno extends Unary {
 public sugeno() {
   super("xfl","sugeno");
   Parameter single[] = new Parameter[1];
   single[0] = new Parameter("l");
   setSingleParameters(single);
  }

 public double compute(double a) {
   double l = singleparam[0].value;
 return (1-a)/(1+a*l); 
  }

 public double derivative(double a) {
   double deriv;
   double l = singleparam[0].value;
 deriv = -(1+l)/((1+l*a)*(1+l*a)); 
   return deriv;
  }

 public boolean test () {
   double l = singleparam[0].value;
   return ( l>-1 );
  }

 public String getJavaCode() {
   String eol = System.getProperty("line.separator", "\n");
   String code = "";
   code += "    return (1-a)/(1+a*l); "+eol;
   return code;
  }

 public String getCCode() {
   String eol = System.getProperty("line.separator", "\n");
   String code = "";
   code += "    return (1-a)/(1+a*l); "+eol;
   return code;
  }

 public String getCppCode() {
   String eol = System.getProperty("line.separator", "\n");
   String code = "";
   code += "    return (1-a)/(1+a*l); "+eol;
   return code;
  }
}
