//+++++++++++++++++++++++++++++++++++++++++++++++++++++
// File automatically generated by Xfuzzy - DO NOT EDIT
//+++++++++++++++++++++++++++++++++++++++++++++++++++++

package pkg.xfl.unary;

import xfuzzy.lang.*;

public class yager extends Unary {
 public yager() {
   super("xfl","yager");
   Parameter single[] = new Parameter[1];
   single[0] = new Parameter("w");
   setSingleParameters(single);
  }

 public double compute(double a) {
   double w = singleparam[0].value;
 return Math.pow( ( 1 - Math.pow(a,w) ) , 1/w ); 
  }

 public double derivative(double a) {
   double deriv;
   double w = singleparam[0].value;
 deriv = - Math.pow( Math.pow(a,-w) -1, (1-w)/w ); 
   return deriv;
  }

 public boolean test () {
   double w = singleparam[0].value;
   return ( w>0 );
  }

 public String getJavaCode() {
   String eol = System.getProperty("line.separator", "\n");
   String code = "";
   code += "    return Math.pow( ( 1 - Math.pow(a,w) ) , 1/w ); "+eol;
   return code;
  }

 public String getCCode() {
   String eol = System.getProperty("line.separator", "\n");
   String code = "";
   code += "    return pow( ( 1 - pow(a,w) ) , 1/w ); "+eol;
   return code;
  }

 public String getCppCode() {
   String eol = System.getProperty("line.separator", "\n");
   String code = "";
   code += "    return pow( ( 1 - pow(a,w) ) , 1/w ); "+eol;
   return code;
  }
}
